pipeline {
    agent any

    stages {
        stage('Backend test') {
            steps {
                dir('practiseB') {
                    bat '.\\mvnw.cmd clean test'
                }
            }
        }
    }
}