pipeline {
    agent any

    stages {
        stage('Check Java') {
            steps {
                bat 'echo JAVA_HOME=%JAVA_HOME%'
                bat '"%JAVA_HOME%\\bin\\java.exe" -version'
            }
        }

        stage('Backend test') {
            steps {
                dir('practiseB') {
                    bat '.\\mvnw.cmd clean test'
                }
            }
        }

        stage('Build backend JAR') {
            steps {
                dir('practiseB') {
                    bat '.\\mvnw.cmd package -DskipTests'
                }
            }
        }

        stage('Show generated JAR') {
            steps {
                dir('practiseB') {
                    bat 'dir target\\*.jar'
                }
            }
        }

        stage('Build Docker image') {
            steps {
                dir('practiseB') {
                    bat 'docker build -t practiseb-backend:%BUILD_NUMBER% .'
                    bat 'docker tag practiseb-backend:%BUILD_NUMBER% practiseb-backend:latest'
                }
            }
        }

        stage('Show Docker image') {
            steps {
                bat 'docker images practiseb-backend'
            }
        }
    }
}