pipeline {
    agent any

    stages {
        stage('Check Java') {
            steps {
                bat 'java -version'
                bat 'echo JAVA_HOME=%JAVA_HOME%'
                bat 'where java'
            }
        }

        stage('Backend test') {
            steps {
                dir('practiseB') {
                    bat '.\\mvnw.cmd clean test'
                }
            }
        }
    }
}